import { uid } from 'uid';
import { Document } from '../types/document';

export const documentsOneResponse: Document[] = [
  {
    id: uid(),
    status: 'active',
    sum: 2000,
    qty: 9,
    volume: 3,
    name: 'Дерево',
    delivery_date: new Date('2013-10-01').toLocaleDateString(),
    currency: 'руб.',
  },
  {
    id: uid(),
    status: 'archive',
    sum: 2312,
    qty: 2,
    volume: 10,
    name: 'Лестница',
    delivery_date: new Date('2022-08-21').toLocaleDateString(),
    currency: 'руб.',
  },
  {
    id: uid(),
    status: 'archive',
    sum: 4123,
    qty: 6,
    volume: 43,
    name: 'Конфеты',
    delivery_date: new Date('2018-02-12').toLocaleDateString(),
    currency: 'руб.',
  },
  {
    id: uid(),
    status: 'active',
    sum: 12512,
    qty: 2,
    volume: 7,
    name: 'Стиральная машина',
    delivery_date: new Date('2017-01-26').toLocaleDateString(),
    currency: 'руб.',
  },
  {
    id: uid(),
    status: 'active',
    sum: 94412,
    qty: 1,
    volume: 3,
    name: 'Компьютер',
    delivery_date: new Date().toLocaleDateString(),
    currency: 'руб.',
  },
];

export const documentsTwoResponse: Document[] = [
  {
    id: uid(),
    status: 'active',
    sum: 34122,
    qty: 1,
    volume: 3,
    name: 'Машина',
    delivery_date: new Date('2012-04-08').toLocaleDateString(),
    currency: 'долл.',
  },
  {
    id: uid(),
    status: 'archive',
    sum: 12000000,
    qty: 1,
    volume: 1,
    name: 'Дом',
    delivery_date: new Date('2022-08-21').toLocaleDateString(),
    currency: 'руб.',
  },
  {
    id: uid(),
    status: 'archive',
    sum: 5412,
    qty: 2,
    volume: 13,
    name: 'Монитор',
    delivery_date: new Date('2019-06-19').toLocaleDateString(),
    currency: 'руб.',
  },
  {
    id: uid(),
    status: 'active',
    sum: 5000,
    qty: 3,
    volume: 3,
    name: 'Компьютерная мышь',
    delivery_date: new Date('2018-03-12').toLocaleDateString(),
    currency: 'руб.',
  },
  {
    id: uid(),
    status: 'active',
    sum: 3000,
    qty: 1,
    volume: 2,
    name: 'Ноутбук',
    delivery_date: new Date('2021-11-19').toLocaleDateString(),
    currency: 'долл.',
  },
];
